Failed checking if argv[0] is an import path entry
Traceback (most recent call last):
  File "<frozen zipimport>", line 92, in __init__
KeyError: '/home/alexander/school/exeter/phd-physics/upgrade_report/case_studies/common/structures/interfaces/336_Sn144Ge192_011_011_a0.0_b0.0_c0.0_interface1shift1/run-mace.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 94, in __init__
  File "<frozen zipimport>", line 358, in _read_directory
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/alexander/school/exeter/phd-physics/upgrade_report/case_studies/common/structures/interfaces/336_Sn144Ge192_011_011_a0.0_b0.0_c0.0_interface1shift1/run-mace.py", line 4, in <module>
    from ase.io import read
  File "/home/alexander/lib/python3.12/site-packages/ase/__init__.py", line 8, in <module>
    import ase.parallel  # noqa
    ^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/lib/python3.12/site-packages/ase/parallel.py", line 9, in <module>
    import numpy as np
  File "/home/alexander/lib/python3.12/site-packages/numpy/__init__.py", line 149, in <module>
    from . import lib
  File "/home/alexander/lib/python3.12/site-packages/numpy/lib/__init__.py", line 23, in <module>
    from . import index_tricks
  File "/home/alexander/lib/python3.12/site-packages/numpy/lib/index_tricks.py", line 12, in <module>
    import numpy.matrixlib as matrixlib
  File "/home/alexander/lib/python3.12/site-packages/numpy/matrixlib/__init__.py", line 4, in <module>
    from . import defmatrix
  File "/home/alexander/lib/python3.12/site-packages/numpy/matrixlib/defmatrix.py", line 12, in <module>
    from numpy.linalg import matrix_power
  File "/home/alexander/lib/python3.12/site-packages/numpy/linalg/__init__.py", line 73, in <module>
    from . import linalg
  File "/home/alexander/lib/python3.12/site-packages/numpy/linalg/linalg.py", line 20, in <module>
    from typing import NamedTuple, Any
  File "/home/alexander/anaconda3/lib/python3.12/typing.py", line 3262, in <module>
    class TextIO(IO[str]):
  File "/home/alexander/anaconda3/lib/python3.12/typing.py", line 3279, in TextIO
    def errors(self) -> Optional[str]:
                        ~~~~~~~~^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/typing.py", line 395, in inner
    return _caches[func](*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/typing.py", line 517, in __getitem__
    return self._getitem(self, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/typing.py", line 751, in Optional
    return Union[arg, type(None)]
           ~~~~~^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/typing.py", line 395, in inner
    return _caches[func](*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/typing.py", line 517, in __getitem__
    return self._getitem(self, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/typing.py", line 735, in Union
    return _UnionGenericAlias(self, parameters, name="Optional")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/typing.py", line 1261, in __init__
    super().__init__(origin, inst=inst, name=name)
  File "/home/alexander/anaconda3/lib/python3.12/typing.py", line 1166, in __init__
    self._inst = inst
    ^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/typing.py", line 1207, in __setattr__
    if _is_dunder(attr) or attr in {'_name', '_inst', '_nparams'}:
       ^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/typing.py", line 1153, in _is_dunder
    return attr.startswith('__') and attr.endswith('__')
           ^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
