Exception ignored in: <function _get_module_lock.<locals>.cb at 0x7f3712425e40>
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 446, in cb
KeyboardInterrupt: 
Traceback (most recent call last):
  File "/home/alexander/school/exeter/phd-physics/upgrade_report/case_studies/common/structures/interfaces/120_Ge48Si72_001_011_a0.0_b0.0_c0.0_interface7shift1swap3/run-mace.py", line 4, in <module>
    from ase.io import read
  File "/home/alexander/lib/python3.12/site-packages/ase/__init__.py", line 8, in <module>
    import ase.parallel  # noqa
    ^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/lib/python3.12/site-packages/ase/parallel.py", line 9, in <module>
    import numpy as np
  File "/home/alexander/lib/python3.12/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/home/alexander/lib/python3.12/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/home/alexander/lib/python3.12/site-packages/numpy/core/__init__.py", line 104, in <module>
    from . import _internal
  File "/home/alexander/lib/python3.12/site-packages/numpy/core/_internal.py", line 7, in <module>
    import ast
  File "/home/alexander/anaconda3/lib/python3.12/ast.py", line 29, in <module>
    from _ast import *
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 946, in _load_unlocked
KeyboardInterrupt
